### ISSUE TITLE
Example for ActiveInventoryList?

### ISSUE THREAD

**Issue by benkraw** [wrhansen/ebay#1]
I was wondering how you can call the ActiveInventoryList.  Do you need to make a bulk data exchange call?  Or can you call the report directly through the wrapper you made?  Do you have any examples of this.

**Comment by wrhansen** [comment]
This `ebay` module only has a select number of Trading API calls supported, however the `BulkDataFile` object was designed to handle any of the calls that eBay supports for LMS calls. I do not have an example of using this for building the `ActiveInventoryReport` call and cannot say for certain if it is even up-to-date with eBay's endpoints. I'm sorry to say this project was scrapped 4 years ago, and I haven't dealt with eBay since.

However, after a quick search through eBay's documentation, I may be able to point you in the right direction. According to their **Samples** section in the [documentation](http://developer.ebay.com/devzone/merchant-data/CallRef/ActiveInventoryReport.html#Samples):

```
User megaonlinemerchant wants to see a list of her active inventory on the eBay site.
She sends a Bulk Data Exchange startDownloadJob request with the ActiveInventoryReport
parameter, uses a Bulk Data Exchange getJobStatus request to see if her report is ready to
download, and then sends a File Transfer Service downloadJob request to retrieve the report data.
```

This tells me that you don't have to construct something for the request, you just have to use the _Large Merchant Services_ (LMS) api calls to request the report. I have another, again 4 years old, module called [eBay-LMS-API](https://github.com/wrhansen/eBay-LMS-API), which you can use for such purposes. All the endpoints for LMS are supported by this module, but again, I can't say for certain if they're still working today.

I hope that helps point you in the right direction.
